import { resolve } from 'path';
import nock from 'nock';
import { JSDOM } from 'jsdom';

const { window } = new JSDOM('<!DOCTYPE html><head></head><body></body>', {
  runScripts: 'dangerously',
  resources: 'usable'
});
const { document } = window;
(globalThis as any).window = window;
globalThis.document = document;

const dummyMessageBus = {} as any;

describe('starters generated by startersBrowserStandalone', () => {
  it('creates a working starter for plain JS', async () => {
    nock('http://localhost:12345').get('/styles.css').reply(200, '');
    nock('http://localhost:12345')
      .get('/Microfrontend.js')
      .reply(
        200,
        `
        window.startMyFirstMicrofrontend = () => {         
           window.__started__ = true;
           return {
            onRemove: () => {
              window.__removed__ = true;
            }
           };          
        };
      `
      );

    const { startMyFirstMicrofrontend } = await import(
      '../_expectations/full1_microfrontendStarters_browser_standalone'
    );

    const hostEl = document.createElement('div');
    document.body.appendChild(hostEl);

    const result = await startMyFirstMicrofrontend('http://localhost:12345', hostEl, {
      id: '1',
      config: {},
      permissions: {
        showDetails: false,
        deletePermitted: false
      },
      messageBus: dummyMessageBus
    });

    expect(window.__started__).toBeTruthy();
    expect(window.__removed__).toBeFalsy();
    expect(result).toBeTruthy();

    await result.close();

    expect(window.__removed__).toBeTruthy();
  });

  it('creates a working starter for ESM modules', async () => {
    const { startMyFirstMicrofrontend } = await import(
      '../_expectations/full1_microfrontendStarters_browser_standalone_ESM'
    );

    const hostEl = document.createElement('div');
    document.body.appendChild(hostEl);

    const result = await startMyFirstMicrofrontend(
      resolve(import.meta.dirname, '_assets', 'microfrontend1_esm'),
      hostEl,
      {
        id: '1',
        config: {},
        permissions: {
          showDetails: false,
          deletePermitted: false
        },
        messageBus: dummyMessageBus
      }
    );

    expect(window.__started2__).toBeTruthy();
    expect(window.__removed2__).toBeFalsy();
    expect(result).toBeTruthy();

    await result.close();

    expect(window.__removed2__).toBeTruthy();
  });

  it('creates a working starter for SystemJS', async () => {
    nock('http://localhost:12345').get('/styles.css').reply(200, '');
    nock('http://localhost:12345')
      .get('/Microfrontend.js')
      .reply(
        200,
        `
        System.register([], function(exports, module) {
          exports('startMyFirstMicrofrontend',() => {
            window.__started__ = true;
            return {
              onRemove: () => {
                window.__removed__ = true;
              }
            };
          });
          return {
            setters: [
            ],
            execute: function() {
            }
          };
        });
      `,
        {
          'Content-Type': 'application/javascript'
        }
      );

    globalThis.System = (await import('systemjs')).default.System;

    const { startMyFirstMicrofrontend } = await import(
      '../_expectations/full1_microfrontendStarters_browser_standalone_SystemJS'
    );

    const hostEl = document.createElement('div');
    document.body.appendChild(hostEl);

    const result = await startMyFirstMicrofrontend('http://localhost:12345', hostEl, {
      id: '1',
      config: {},
      permissions: {
        showDetails: false,
        deletePermitted: false
      },
      messageBus: dummyMessageBus
    });

    expect(window.__started__).toBeTruthy();
    expect(window.__removed__).toBeFalsy();
    expect(result).toBeTruthy();

    await result.close();

    expect(window.__removed__).toBeTruthy();
  });
});
