import nock from 'nock';
import { JSDOM } from 'jsdom';

const { window } = new JSDOM('<!DOCTYPE html><head></head><body></body>', {
  runScripts: 'dangerously',
  resources: 'usable',
  url: 'http://localhost:5432',
});
const { document } = window;
(globalThis as any).window = window;
globalThis.document = document;
(globalThis as any).location = {
  href: 'http://localhost:5432',
};

const dummyMessageBus = {} as any;

describe('starters generated by the starters template', () => {
  beforeEach(() => {
    nock.cleanAll();
  });

  it('creates a working Starter', async () => {
    nock('http://localhost:5432')
      .get('/__open_microfrontends__/MyFirstMicrofrontend/setup')
      .reply(200, {
        lang: 'en',
        user: {
          username: 'maria',
          displayName: 'Maria Gonzales',
        },
        permissions: {
          showDetails: true,
          deletePermitted: true,
        },
        hostContext: {
          hostApplicationName: 'Jest',
        },
        assetBuildTimestampOrVersion: '1.0.0',
      });
    nock('http://localhost:5432')
      .get('/__open_microfrontends__/MyFirstMicrofrontend/assets/styles.css')
      .query('v=1.0.0')
      .reply(200, '');
    nock('http://localhost:5432')
      .get('/__open_microfrontends__/MyFirstMicrofrontend/assets/Microfrontend.js')
      .query('v=1.0.0')
      .reply(
        200,
        `
        window.startMyFirstMicrofrontend = (hostEl, context) => {         
           window.__started__ = true;
           window.__context__ = context;
           return {
            onRemove: () => {
              window.__removed__ = true;
            }
           };          
        };
      `
      );

    const { startMyFirstMicrofrontend } = await import('../_expectations/full_microfrontendStarters');

    const hostEl = document.createElement('div');
    document.body.appendChild(hostEl);

    const result = await startMyFirstMicrofrontend(hostEl, {
      id: '1',
      config: {},
      messageBus: dummyMessageBus,
    });

    expect(window.__started__).toBeTruthy();
    expect(window.__context__).toEqual({
      apiProxyPaths: {
        proxy1: '/__open_microfrontends__/MyFirstMicrofrontend/proxies/proxy1',
        proxy2: '/__open_microfrontends__/MyFirstMicrofrontend/proxies/proxy2',
      },
      config: {
        customerId: '1000',
      },
      hostContext: {
        hostApplicationName: 'Jest',
      },
      id: '1',
      lang: 'en',
      messageBus: {},
      permissions: {
        deletePermitted: true,
        showDetails: true,
      },
      user: {
        displayName: 'Maria Gonzales',
        username: 'maria',
      },
      serverSideRendered: false,
    });
    expect(window.__removed__).toBeFalsy();
    expect(result).toBeTruthy();

    await result.close();

    expect(window.__removed__).toBeTruthy();
  });
});
