import { resolve } from 'path';
import { readFileSync } from 'fs';
import nock from 'nock';
import { JSDOM } from 'jsdom';

const { window } = new JSDOM('<!DOCTYPE html><head></head><body></body>', {
  runScripts: 'dangerously',
  resources: 'usable',
});
const { document } = window;
(globalThis as any).window = window;
globalThis.document = document;

const dummyMessageBus = {} as any;

describe('starters generated by the startersBrowserStandalone template', () => {
  beforeEach(() => {
    nock.cleanAll();
  });

  it('creates a working starter', async () => {
    nock('http://localhost:12345').get('/styles.css').query(true).reply(200, '');
    nock('http://localhost:12345')
      .get('/Microfrontend.js')
      .query(true)
      .reply(
        200,
        `
        window.startMyFirstMicrofrontend = () => {         
           window.__started__ = true;
           return {
            onRemove: () => {
              window.__removed__ = true;
            }
           };          
        };
      `
      );

    const { startMyFirstMicrofrontend } = await import(
      '../_expectations/full_microfrontendStarters_browser_standalone'
    );

    const hostEl = document.createElement('div');
    document.body.appendChild(hostEl);

    const result = await startMyFirstMicrofrontend('http://localhost:12345', hostEl, {
      id: '1',
      config: {},
      permissions: {
        showDetails: false,
        deletePermitted: false,
      },
      messageBus: dummyMessageBus,
    });

    expect(window.__started__).toBeTruthy();
    expect(window.__removed__).toBeFalsy();
    expect(result).toBeTruthy();

    await result.close();

    expect(window.__removed__).toBeTruthy();
  });

  it('creates a working starter for ESM modules', async () => {
    const { startMyFirstMicrofrontend } = await import(
      '../_expectations/fullESM_microfrontendStarters_browser_standalone'
    );

    const hostEl = document.createElement('div');
    document.body.appendChild(hostEl);

    const result = await startMyFirstMicrofrontend(
      resolve(import.meta.dirname, '_assets', 'microfrontend1_esm'),
      hostEl,
      {
        id: '1',
        config: {},
        permissions: {
          showDetails: false,
          deletePermitted: false,
        },
        messageBus: dummyMessageBus,
      }
    );

    expect(window.__started2__).toBeTruthy();
    expect(window.__removed2__).toBeFalsy();
    expect(result).toBeTruthy();

    await result.close();

    expect(window.__removed2__).toBeTruthy();
  });

  it('creates a working starter for SystemJS', async () => {
    nock('http://localhost:12345').get('/styles.css').query(true).reply(200, '');
    nock('http://localhost:12345')
      .get('/Microfrontend.js')
      .query(true)
      .reply(
        200,
        `
        System.register([], function(exports, context) {
          return {
            setters: [
            ],
            execute: function() {
              exports('startMyFirstMicrofrontend', async () => {
                const module2 = await context.import('module2');
                window.__started3__ = true;
                return {
                  onRemove: () => {
                    window.__removed3__ = true;
                  }
                };
              });            
            }
          };
        });
      `,
        {
          'Content-Type': 'application/javascript',
        }
      );
    nock('http://localhost:12345')
      .get('/module2.js')
      .reply(
        200,
        `
        System.register([], function(exports, module) {       
          return {
            setters: [
            ],
            execute: function() {
               window.__module2_loaded__ = true;    
            }
          };
        });
      `,
        {
          'Content-Type': 'application/javascript',
        }
      );

    // Load SystemJS
    const systemJsdScript = document.createElement('script');
    systemJsdScript.innerHTML = readFileSync(resolve(import.meta.dirname, '_assets', 'system_6_15_1.min.js'), 'utf-8');
    document.head.appendChild(systemJsdScript);
    globalThis.System = window.System;

    const { startMyFirstMicrofrontend } = await import(
      '../_expectations/fullSystemJS_microfrontendStarters_browser_standalone'
    );

    const hostEl = document.createElement('div');
    document.body.appendChild(hostEl);

    const result = await startMyFirstMicrofrontend('http://localhost:12345', hostEl, {
      id: '1',
      config: {},
      permissions: {
        showDetails: false,
        deletePermitted: false,
      },
      messageBus: dummyMessageBus,
    });

    expect(window.__started3__).toBeTruthy();
    expect(window.__module2_loaded__).toBeTruthy();
    expect(window.__removed3__).toBeFalsy();
    expect(result).toBeTruthy();
    expect(window.System.getImportMap()).toEqual({
      imports: {
        'http://localhost:12345/Microfrontend.js': `http://localhost:12345/Microfrontend.js?v=${Math.floor(Date.now() / 10000) * 10}`,
        module1: 'http://localhost:12345/module1.js',
        module2: 'http://localhost:12345/module2.js',
      },
      scopes: {},
      depcache: {},
      integrity: {},
    });

    await result.close();

    expect(window.__removed3__).toBeTruthy();

    document.body.removeChild(hostEl);
    document.head.removeChild(systemJsdScript);
  });

  it('creates a working starter for SystemJS that deals correctly with the pre-existing importmap', async () => {
    nock('http://localhost:12345').get('/styles.css').query(true).reply(200, '');
    nock('http://localhost:12345')
      .get('/Microfrontend.js')
      .query(true)
      .reply(
        200,
        `
        System.register([], function(exports, context) {
          return {
            setters: [
            ],
            execute: function() {
              exports('startMyFirstMicrofrontend', async () => {
                const { func2 } = await context.import('module2');
                await func2();
                window.__started4__ = true;              
                return {
                  onRemove: () => {
                    window.__removed4__ = true;
                  }
                };
              });
            }
          };
        });
      `,
        {
          'Content-Type': 'application/javascript',
        }
      );
    nock('http://localhost:12345')
      .get('/module2.js')
      .reply(
        200,
        `
        System.register([], function(exports, context) {  
          return {
            setters: [
            ],
            execute: function() {
             exports('func2', async () => await context.import('module1'));
             window.__module2_loaded2__ = true; 
            }
          };
        });
      `,
        {
          'Content-Type': 'application/javascript',
        }
      );
    nock('http://localhost:12345')
      .get('/module1.js')
      .reply(
        200,
        `
        System.register([], function(exports, context) {
          return {
            setters: [
            ],
            execute: function() {
              window.__module1_loaded__ = true;      
            }
          };
        });
      `,
        {
          'Content-Type': 'application/javascript',
        }
      );

    // Load SystemJS
    const systemJsdScript = document.createElement('script');
    systemJsdScript.innerHTML = readFileSync(resolve(import.meta.dirname, '_assets', 'system_6_15_1.min.js'), 'utf-8');
    document.head.appendChild(systemJsdScript);
    globalThis.System = window.System;

    globalThis.System.addImportMap({
      imports: {
        module1: 'http://localhost:3333/module1.js',
        module2: 'http://localhost:3333/module2.js',
      },
    });

    const { startMyFirstMicrofrontend } = await import(
      '../_expectations/fullSystemJS_microfrontendStarters_browser_standalone'
    );

    const hostEl = document.createElement('div');
    document.body.appendChild(hostEl);

    const result = await startMyFirstMicrofrontend('http://localhost:12345', hostEl, {
      id: '1',
      config: {},
      permissions: {
        showDetails: false,
        deletePermitted: false,
      },
      messageBus: dummyMessageBus,
    });

    expect(window.__started4__).toBeTruthy();
    expect(window.__module2_loaded2__).toBeTruthy();
    expect(window.__module1_loaded__).toBeTruthy();
    expect(window.__removed4__).toBeFalsy();
    expect(result).toBeTruthy();
    expect(window.System.getImportMap()).toEqual({
      depcache: {},
      imports: {
        'http://localhost:12345/Microfrontend.js': `http://localhost:12345/Microfrontend.js?v=${Math.floor(Date.now() / 10000) * 10}`,
        module1: 'http://localhost:3333/module1.js',
        module2: 'http://localhost:3333/module2.js',
      },
      integrity: {},
      scopes: {
        [`http://localhost:12345/Microfrontend.js?v=${Math.floor(Date.now() / 10000) * 10}`]: {
          module1: 'http://localhost:12345/module1.js',
          module2: 'http://localhost:12345/module2.js',
        },
        'http://localhost:12345/module1.js': {
          'http://localhost:12345/Microfrontend.js': `http://localhost:12345/Microfrontend.js?v=${Math.floor(Date.now() / 10000) * 10}`,
          module1: 'http://localhost:12345/module1.js',
          module2: 'http://localhost:12345/module2.js',
        },
        'http://localhost:12345/module2.js': {
          'http://localhost:12345/Microfrontend.js': `http://localhost:12345/Microfrontend.js?v=${Math.floor(Date.now() / 10000) * 10}`,
          module1: 'http://localhost:12345/module1.js',
          module2: 'http://localhost:12345/module2.js',
        },
      },
    });

    await result.close();

    expect(window.__removed4__).toBeTruthy();

    document.body.removeChild(hostEl);
    document.head.removeChild(systemJsdScript);
  });
});
