/**
 * This file was automatically generated by OMG (OpenMicrofrontend Generator).
 * DO NOT MODIFY!
 */

import type { OpenMicrofrontendsClientContext } from '@open-microfrontends/types/OpenMicrofrontendsRendererFunction';

// Helper

function addCssLinkTag(url: string, addedElements: Array<HTMLElement>): void {
  const linkElem = document.createElement('link');
  linkElem.rel = 'stylesheet';
  linkElem.href = url;
  linkElem.addEventListener('error', (error) => {
    console.error('[OpenMicrofrontends] Error loading CSS resource: ', url, error);
  });
  document.head.appendChild(linkElem);
  addedElements.push(linkElem);
}

function toFullUrl(...parts: Array<string>): string {
  return parts
    .map((part) => (part.endsWith('/') ? part.slice(0, -1) : part))
    .map((part, idx) => (idx > 0 && part && !part.startsWith('/') ? `/${part}` : part))
    .join('');
}

/* TypeScript type from Schemas */

export interface Microfrontend1Config {
  customerId: string;
}

export interface Microfrontend1TopicPing {
  ping: true;
  [k: string]: unknown;
}

/* Type Parameters */

type Microfrontend1Permissions = {
  readonly showDetails: boolean;

  readonly deletePermitted: boolean;
};

type Microfrontend1MessagesPublish = Record<string, any>;
type Microfrontend1MessagesSubscribe = Record<string, any>;

/* Type-safe MessageBus slice for the client */

type Microfrontend1ClientMessageBus = {
  publish(topic: 'ping', data: Microfrontend1TopicPing): void;

  subscribe(topic: 'ping', cb: (data: Microfrontend1TopicPing) => void): void;
  unsubscribe(topic: 'ping', cb: (data: Microfrontend1TopicPing) => void): void;
};

/* Default config  */

const defaultConfig = {
  customerId: '1000'
};

/* Render function type with aligned config and message bus */

type Microfrontend1ClientContext = OpenMicrofrontendsClientContext<
  Partial<Microfrontend1Config>,
  Microfrontend1Permissions,
  undefined,
  Microfrontend1MessagesPublish,
  Microfrontend1MessagesSubscribe
>;

/* Start function */

export async function startMyFirstMicrofrontend(
  serverUrl: string,
  hostElement: HTMLElement,
  context: Microfrontend1ClientContext
) {
  const addedElements: Array<HTMLElement> = [];
  const exportedModules: Array<any> = [];

  // Add stylesheets

  addCssLinkTag(toFullUrl(serverUrl, '/', 'styles.css'), addedElements);

  const jsUrls = [toFullUrl(serverUrl, '/', 'Microfrontend.js')];

  // Load initial modules consecutively (ESM)
  try {
    for (const jsUrl of jsUrls) {
      const module = await import(jsUrl);
      if (module) {
        exportedModules.push(module);
      }
    }
  } catch (e) {
    console.error('[OpenMicrofrontends] Loading assets of Microfrontend "My First Microfrontend" failed!', e);
    return;
  }

  // Start Microfrontend
  const renderFunction =
    exportedModules.find((m) => 'startMyFirstMicrofrontend' in m)?.['startMyFirstMicrofrontend'] ||
    (window as any)['startMyFirstMicrofrontend'];
  if (!renderFunction) {
    console.error('[OpenMicrofrontends] Render function of Microfrontend "My First Microfrontend" not found!');
    return;
  }

  const contextWithDefaultConfig = {
    ...context,
    config: {
      ...defaultConfig,
      ...context.config
    }
  };
  const lifecycleHooks = await renderFunction(hostElement, contextWithDefaultConfig);

  return {
    close: async () => {
      console.info('[OpenMicrofrontends] Closing Microfrontend "My First Microfrontend"');
      await lifecycleHooks?.onRemove();
      addedElements.forEach((elem) => elem.remove());
      hostElement.innerHTML = '';
    },

    messages: context.messageBus as Microfrontend1ClientMessageBus
  };
}
