/* eslint-disable */
/**
* This file was automatically generated by OMG (OpenMicrofrontend Generator).
* DO NOT MODIFY!
*/

import {MashroomPortalClientServices} from '@mashroom/mashroom-portal/type-definitions';

/* Config Types */
    export interface Microfrontend1Config {
  customerId: string;
}


/* Message Types */
            export interface Microfrontend1TopicPing {
  ping: true;
  [k: string]: unknown;
}

    

type OpenMicrofrontendLifecycleHooks = {
    readonly onRemove?: () => void | Promise<void>;
};

type Partial<T> = {
    [P in keyof T]?: T[P];
};


    

type Microfrontend1ClientMessageBus = {

    
    publish(topic: 'ping', data: Microfrontend1TopicPing): void;
    
    
    subscribe(topic: 'ping', cb: (data: Microfrontend1TopicPing) => void): void;
    unsubscribe(topic: 'ping', cb: (data: Microfrontend1TopicPing) => void): void;
    

};


    
// Start function for Microfrontend: My First Microfrontend
export async function startMyFirstMicrofrontend(hostElementId: string, overrideConfig?: Partial<Microfrontend1Config>) {
    const clientServices = (window as any).MashroomPortalServices as MashroomPortalClientServices | undefined;
    if (!clientServices) {
        throw new Error('OpenMicrofrontends: Mashroom Portal not available!');
    }

    const portalApp = await clientServices.portalAppService.loadApp(hostElementId, 'My First Microfrontend', undefined, undefined, overrideConfig);

    return {
        id: portalApp.id,
        close: async () => {
            await clientServices.portalAppService.unloadApp(portalApp.id);
        },
        
        messages: clientServices.messageBus as Microfrontend1ClientMessageBus,
        
    };
}


