/**
 * This file was automatically generated by OMG (OpenMicrofrontends Generator).
 * DO NOT MODIFY!
 */

import type { OpenMicrofrontendsServerSideRenderer } from '@open-microfrontends/types/OpenMicrofrontendsServerSideRenderer';

/* TypeScript type from Schemas */

export interface Microfrontend1Config {
  customerId: string;
}

export interface Microfrontend1TopicPing {
  ping: true;
  [k: string]: unknown;
}

/* --- Microfrontend 1 --- */

/* Type Parameters */

type Microfrontend1Permissions = {
  readonly showDetails: boolean;

  readonly deletePermitted: boolean;
};

/* Renderer */

export type MyFirstMicrofrontendServerSideRenderer = OpenMicrofrontendsServerSideRenderer<
  Microfrontend1Config,
  Microfrontend1Permissions
>;

/* Path constants */

export const MyFirstMicrofrontendServerSideRendererPath = '/ssr';
