/* eslint-disable */
/**
* This file was automatically generated by OMG (OpenMicrofrontend Generator).
* DO NOT MODIFY!
*/

/* Config Types */
export interface Microfrontend1Config {
  customerId: string;
}


/* Message Types */
export interface Microfrontend1TopicPing {
  ping: true;
  [k: string]: unknown;
}

    

type OpenMicrofrontendLifecycleHooks = {
    readonly onRemove?: () => void | Promise<void>;
};

type Partial<T> = {
    [P in keyof T]?: T[P];
};


// Render context for Microfrontend: My First Microfrontend
type Microfrontend1Context = {
    // The unique ID of this Microfrontend instance
    readonly id: string;
    // Two-letter language code (e.g., "fr")
    readonly lang: string;
    readonly user: {
        readonly guest: boolean;
        readonly username: string;
        readonly displayName: string;
        
        readonly permissions: {
            
            readonly 'perm1': boolean;
            
        };
        
    },
    
    readonly apiProxyPaths: {
        
        readonly 'proxy1': string;
        
        readonly 'proxy2': string;
        
    },
    
    readonly config: Microfrontend1Config;
    
    readonly messageBus: {
        
        
        publish(topic: 'ping', data: Microfrontend1TopicPing): void;
        
        
        subscribe(topic: 'ping', cb: (data: Microfrontend1TopicPing) => void): void;
        unsubscribe(topic: 'ping', cb: (data: Microfrontend1TopicPing) => void): void;
        
        
    };
    
}


type Microfrontend1RenderCb = (hostElement: HTMLElement, context: Microfrontend1Context) => Promise<OpenMicrofrontendLifecycleHooks>;

// Render function for Microfrontend: My First Microfrontend
export function onRenderMyFirstMicrofrontend(cb: Microfrontend1RenderCb): void {

    (window as any)['startMyFirstMicrofrontend'] = async (hostElement: HTMLElement, ...otherArgs: any[]) => {
        // Temporary Mashroom Server compatibility, until it supports OpenMicrofrontends natively
        const enableTempMashroomComp = otherArgs.length === 2 && otherArgs[0].appId && otherArgs[0].proxyPaths;

        const defaultContext: Omit<Microfrontend1Context, 'apiProxyPaths'> = {
            id: 'default',
            lang: 'en',
            user: {
                guest: true,
                username: 'guest',
                displayName: 'guest',
                
                permissions: {} as any,
                
            },
            config: {
    "customerId": "1000"
},
            
            messageBus: {
                publish(topic: any) { console.warn(`OpenMicrofrontends: Publish to topic ${topic} but no messageBus present!`); },
                subscribe(topic: any) { console.warn(`OpenMicrofrontends: Subscribe to topic ${topic} but no messageBus present!`); },
                unsubscribe(topic: any) {},
            },
            
        };

        let context: Microfrontend1Context;
        if (enableTempMashroomComp) {
            const {appId, lang, user, proxyPaths, appConfig} = otherArgs[0];
            const {messageBus} = otherArgs[1];
            context = {
                ...defaultContext,
                id: appId,
                lang,
                user,
                
                apiProxyPaths: proxyPaths,
                
                config: appConfig,
                
                messageBus,
                
            };
        } else {
            // Default
            context = {
                ...defaultContext,
                ...otherArgs[0],
            };
        }

        // Validate
        
        if (!context.apiProxyPaths) {
            throw new Error('OpenMicrofrontends: No apiProxyPaths provided!');
        }
        
        console.debug('OpenMicrofrontends: Starting Microfrontend "My First Microfrontend" with context:', context);
        const result = await cb(hostElement, context);

        if (enableTempMashroomComp) {
            return {
                willBeRemoved: result?.onRemove,
            };
        }
        return result;
    }
}

