/**
 * This file was automatically generated by OMG (OpenMicrofrontend Generator).
 * DO NOT MODIFY!
 */

import type { OpenMicrofrontendsRendererFunction } from '@open-microfrontends/types/OpenMicrofrontendsRendererFunction';

/* TypeScript type from Schemas */

export interface Microfrontend1Config {
  customerId: string;
}

export interface Microfrontend1TopicPing {
  ping: true;
  [k: string]: unknown;
}

/* --- Microfrontend 1 --- */

/* Type Parameters */

type Microfrontend1Permissions = {
  readonly showDetails: boolean;

  readonly deletePermitted: boolean;
};

type Microfrontend1ApiProxyPaths = {
  readonly proxy1: string;

  readonly proxy2: string;
};

type Microfrontend1MessagesPublish = {
  ping: Microfrontend1TopicPing;
};
type Microfrontend1MessagesSubscribe = {
  ping: Microfrontend1TopicPing;
};

/* Render Function */

export type Microfrontend1RenderFunction = OpenMicrofrontendsRendererFunction<
  Microfrontend1Config,
  Microfrontend1Permissions,
  Microfrontend1ApiProxyPaths,
  Microfrontend1MessagesPublish,
  Microfrontend1MessagesSubscribe
>;

export const Microfrontend1RenderFunctionName = 'startMyFirstMicrofrontend';
