/**
 * This file was automatically generated by OMG (OpenMicrofrontend Generator).
 * DO NOT MODIFY!
 */

import type { OpenMicrofrontendsClientContext } from '@open-microfrontends/types/OpenMicrofrontendsRendererFunction';

// Helper

function addCssLinkTag(url: string, addedElements: Array<HTMLElement>): void {
  const linkElem = document.createElement('link');
  linkElem.rel = 'stylesheet';
  linkElem.href = url;
  linkElem.addEventListener('error', (error) => {
    console.error('[OpenMicrofrontends] Error loading CSS resource: ', url, error);
  });
  document.head.appendChild(linkElem);
  addedElements.push(linkElem);
}

function toFullUrl(...parts: Array<string>): string {
  return parts
    .map((part) => (part.endsWith('/') ? part.slice(0, -1) : part))
    .map((part, idx) => (idx > 0 && part && !part.startsWith('/') ? `/${part}` : part))
    .join('');
}

declare var System: any;

function installSystemJSImportMap(initialModules: Array<string>, importMap: any) {
  if (!importMap.imports) {
    return;
  }
  const currentImportMap = System.getImportMap();
  const newImportMap = { imports: {}, scopes: {} };
  for (const _import in importMap.imports) {
    if (!currentImportMap.imports[_import]) {
      newImportMap.imports[_import] = importMap.imports[_import];
    } else if (currentImportMap.imports[_import] !== importMap.imports[_import]) {
      // Conflicting import map entries
      initialModules.forEach((moduleUrl) => {
        if (!(moduleUrl in newImportMap.scopes)) {
          newImportMap.scopes[moduleUrl] = {};
        }
        newImportMap.scopes[moduleUrl][_import] = importMap.imports[_import];
        // Also make sure conflicting entries only load modules from "their" import map
        newImportMap.scopes[importMap.imports[_import]] = {
          ...importMap.imports
        };
      });
    }
  }
  System.addImportMap(newImportMap);
}

/* TypeScript type from Schemas */

export interface Microfrontend1Config {
  customerId: string;
}

export interface Microfrontend1TopicPing {
  ping: true;
  [k: string]: unknown;
}

/* Type Parameters */

type Microfrontend1Permissions = {
  readonly showDetails: boolean;

  readonly deletePermitted: boolean;
};

type Microfrontend1MessagesPublish = Record<string, any>;
type Microfrontend1MessagesSubscribe = Record<string, any>;

/* Type-safe MessageBus slice for the client */

type Microfrontend1ClientMessageBus = {
  publish(topic: 'ping', data: Microfrontend1TopicPing): void;

  subscribe(topic: 'ping', cb: (data: Microfrontend1TopicPing) => void): void;
  unsubscribe(topic: 'ping', cb: (data: Microfrontend1TopicPing) => void): void;
};

/* Default config  */

const defaultConfig = {
  customerId: '1000'
};

/* Render function type with aligned config and message bus */

type Microfrontend1ClientContext = OpenMicrofrontendsClientContext<
  Partial<Microfrontend1Config>,
  Microfrontend1Permissions,
  undefined,
  Microfrontend1MessagesPublish,
  Microfrontend1MessagesSubscribe
>;

/* Start function */

export async function startMyFirstMicrofrontend(
  serverUrl: string,
  hostElement: HTMLElement,
  context: Microfrontend1ClientContext
) {
  const addedElements: Array<HTMLElement> = [];
  const exportedModules: Array<any> = [];

  // Add stylesheets

  addCssLinkTag(toFullUrl(serverUrl, '/', 'styles.css'), addedElements);

  const jsUrls = [toFullUrl(serverUrl, '/', 'Microfrontend.js')];

  // Load initial modules consecutively (SystemJS)
  if (typeof System === 'undefined') {
    throw new Error(
      '[OpenMicrofrontends] Microfrontend "My First Microfrontend" requires SystemJS but is not available!'
    );
  }
  const moduleUrls = [toFullUrl(serverUrl, '/', 'Microfrontend.js')];

  installSystemJSImportMap(moduleUrls, {
    imports: {
      module1: 'http://localhost:12345/module1.js',
      module2: 'http://localhost:12345/module2.js'
    }
  });

  try {
    for (const jsUrl of jsUrls) {
      const module = await System.import(jsUrl);
      if (module) {
        exportedModules.push(module);
      }
    }
  } catch (e) {
    console.error('[OpenMicrofrontends] Loading assets of Microfrontend "My First Microfrontend" failed!', e);
    throw new Error('[OpenMicrofrontends] Loading assets of Microfrontend "My First Microfrontend" failed!');
  }

  // Start Microfrontend
  const renderFunction =
    exportedModules.find((m) => 'startMyFirstMicrofrontend' in m)?.['startMyFirstMicrofrontend'] ||
    exportedModules.find((m) => 'default' in m && 'startMyFirstMicrofrontend' in m.default)?.default?.[
      'startMyFirstMicrofrontend'
    ] ||
    (window as any)['startMyFirstMicrofrontend'];
  if (!renderFunction) {
    throw new Error('[OpenMicrofrontends] Render function of Microfrontend "My First Microfrontend" not found!');
  }

  const contextWithDefaultConfig = {
    ...context,
    config: {
      ...defaultConfig,
      ...context.config
    }
  };
  const lifecycleHooks = await renderFunction(hostElement, contextWithDefaultConfig);

  return {
    close: async () => {
      console.info('[OpenMicrofrontends] Closing Microfrontend "My First Microfrontend"');
      await lifecycleHooks?.onRemove();
      addedElements.forEach((elem) => elem.remove());
      hostElement.innerHTML = '';
    },

    messages: context.messageBus as Microfrontend1ClientMessageBus
  };
}
