/**
 * This file was automatically generated by OMG (OpenMicrofrontend Generator).
 * DO NOT MODIFY!
 */

import type { OpenMicrofrontendsClientContext } from '@open-microfrontends/types/OpenMicrofrontendsRendererFunction';

// Helper

function addJsScriptTag(url: string, addedElements: Array<HTMLElement>): Promise<void> {
  return new Promise((resolve, reject) => {
    const scriptElem = document.createElement('script');
    scriptElem.src = url;
    scriptElem.addEventListener('error', (error) => {
      console.error('[OpenMicrofrontends] Error loading JS resource: ', url, error);
      reject(error);
    });
    scriptElem.addEventListener('load', () => {
      resolve();
    });
    document.head.appendChild(scriptElem);
    addedElements.push(scriptElem);
  });
}

function addCssLinkTag(url: string, addedElements: Array<HTMLElement>): void {
  const linkElem = document.createElement('link');
  linkElem.rel = 'stylesheet';
  linkElem.href = url;
  linkElem.addEventListener('error', (error) => {
    console.error('[OpenMicrofrontends] Error loading CSS resource: ', url, error);
  });
  document.head.appendChild(linkElem);
  addedElements.push(linkElem);
}

function toFullUrl(...parts: Array<string>): string {
  return parts
    .map((part) => (part.endsWith('/') ? part.slice(0, -1) : part))
    .map((part, idx) => (idx > 0 && part && !part.startsWith('/') ? `/${part}` : part))
    .join('');
}

/* TypeScript type from Schemas */

export interface Microfrontend1Config {
  customerId: string;
}

export interface Microfrontend1TopicPing {
  ping: true;
  [k: string]: unknown;
}

/* Asset query timestamp for cache busting */

const assetTimestamp = Math.floor(Date.now() / 10000) * 10;

/* Type Parameters */

type Microfrontend1Permissions = {
  readonly showDetails: boolean;

  readonly deletePermitted: boolean;
};

type Microfrontend1MessagesPublish = Record<string, any>;
type Microfrontend1MessagesSubscribe = Record<string, any>;

/* Type-safe MessageBus slice for the client */

type Microfrontend1ClientMessageBus = {
  publish(topic: 'ping', data: Microfrontend1TopicPing): void;

  subscribe(topic: 'ping', cb: (data: Microfrontend1TopicPing) => void): void;
  unsubscribe(topic: 'ping', cb: (data: Microfrontend1TopicPing) => void): void;
};

/* Default config  */

const defaultConfig = {
  customerId: '1000'
};

/* Render function type with aligned config and message bus */

type Microfrontend1ClientContext = Omit<
  OpenMicrofrontendsClientContext<
    Partial<Microfrontend1Config>,
    Microfrontend1Permissions,
    undefined,
    Microfrontend1MessagesPublish,
    Microfrontend1MessagesSubscribe
  >,
  'apiProxyPaths' | 'serverSideRendered'
>;

/* Start function */

export async function startMyFirstMicrofrontend(
  serverUrl: string,
  hostElement: HTMLElement,
  context: Microfrontend1ClientContext
) {
  const addedElements: Array<HTMLElement> = [];
  const exportedModules: Array<any> = [];

  // Add stylesheets

  addCssLinkTag(toFullUrl(serverUrl, '/', `styles.css?v=${assetTimestamp}`), addedElements);

  const jsUrls = [toFullUrl(serverUrl, '/', `Microfrontend.js?v=${assetTimestamp}`)];

  // Load JS assets consecutively (no modules)
  try {
    for (const jsUrl of jsUrls) {
      await addJsScriptTag(jsUrl, addedElements);
    }
  } catch (e) {
    console.error('[OpenMicrofrontends] Loading assets of Microfrontend "My First Microfrontend" failed!', e);
    throw new Error('[OpenMicrofrontends] Loading assets of Microfrontend "My First Microfrontend" failed!');
  }

  // Start Microfrontend
  const renderFunction =
    exportedModules.find((m) => 'startMyFirstMicrofrontend' in m)?.['startMyFirstMicrofrontend'] ||
    exportedModules.find((m) => 'default' in m && 'startMyFirstMicrofrontend' in m.default)?.default?.[
      'startMyFirstMicrofrontend'
    ] ||
    (window as any)['startMyFirstMicrofrontend'];
  if (!renderFunction) {
    throw new Error('[OpenMicrofrontends] Render function of Microfrontend "My First Microfrontend" not found!');
  }

  const contextWithDefaultConfig = {
    ...context,
    config: {
      ...defaultConfig,
      ...context.config
    }
  };
  const lifecycleHooks = await renderFunction(hostElement, contextWithDefaultConfig);

  return {
    close: async () => {
      console.info('[OpenMicrofrontends] Closing Microfrontend "My First Microfrontend"');
      await lifecycleHooks?.onRemove();
      addedElements.forEach((elem) => elem.remove());
      hostElement.innerHTML = '';
    },

    messages: context.messageBus as Microfrontend1ClientMessageBus
  };
}
