/* eslint-disable */
/**
* This file was automatically generated by OMG (OpenMicrofrontend Generator).
* DO NOT MODIFY!
*/

/* Config Types */
    export interface Microfrontend1Config {
  customerId: string;
}


/* Message Types */
            export interface Microfrontend1TopicPing {
  ping: true;
  [k: string]: unknown;
}

    

type OpenMicrofrontendLifecycleHooks = {
    readonly onRemove?: () => void | Promise<void>;
};

type Partial<T> = {
    [P in keyof T]?: T[P];
};


// Helper

function loadJsResource(url: string): Promise<void> {
    return new Promise((resolve, reject) => {
        const scriptElem = document.createElement('script');
        scriptElem.src = url;
        if (url.endsWith('.mjs')) {
            scriptElem.type = 'module';
        }
        scriptElem.addEventListener('error', (error) => {
            console.error('OpenMicrofrontends: Error loading JS resource: ', url, error);
            reject(error);
        });
        scriptElem.addEventListener('load', () => {
            resolve();
        });
        document.head.appendChild(scriptElem);
    });
 }

function loadCssResource(url: string): void {
    const linkElem = document.createElement('link');
    linkElem.rel = 'stylesheet';
    linkElem.href = url;
    linkElem.addEventListener('error', (error) => {
        console.error('OpenMicrofrontends: Error loading CSS resource: ', url, error);
    });
    document.head.appendChild(linkElem);
}

function toFullUrl(...parts: Array<string>): string {
    return parts
        .map((part) => part.endsWith('/') ? part.slice(0, -1) : part)
        .map((part, idx) => idx > 0 && !part.startsWith('/') ? `/${part}` : part)
        .join('');
}

    // Client context for Microfrontend: My First Microfrontend
type Microfrontend1Context = {
    // The unique ID of this Microfrontend instance
    readonly id?: string;
    // Two-letter language code (e.g., "fr")
    readonly lang?: string;
    readonly user?: {
        readonly guest: boolean;
        readonly username: string;
        readonly displayName: string;
        
        readonly permissions: {
            
            readonly 'perm1': boolean;
            
        };
        
    },
    
    readonly apiProxyPaths: {
        
        readonly 'proxy1': string;
        
        readonly 'proxy2': string;
        
    },
    
    readonly config: Partial<Microfrontend1Config>;
    
    readonly messageBus: {
        publish(topic: string, data: object): void;
        subscribe(topic: string, cb: (data: object) => void): void;
        unsubscribe(topic: string, cb: (data: object) => void): void;
    };
    
}

    

type Microfrontend1ClientMessageBus = {

    
    publish(topic: 'ping', data: Microfrontend1TopicPing): void;
    
    
    subscribe(topic: 'ping', cb: (data: Microfrontend1TopicPing) => void): void;
    unsubscribe(topic: 'ping', cb: (data: Microfrontend1TopicPing) => void): void;
    

};


    
// Start function for Microfrontend: My First Microfrontend
export async function startMyFirstMicrofrontend(serverUrl: string, hostElement: HTMLElement, context: Microfrontend1Context) {
    // Load resources
    const jsPromises: Array<Promise<void>> = [
        
        loadJsResource(toFullUrl(serverUrl, '/', 'app.js')),
        
    ];
    
    
    loadCssResource(toFullUrl(serverUrl, '/', 'app.css'));
    
    

    try {
        await Promise.all(jsPromises);
    } catch (e) {
        console.error('OpenMicrofrontends: Loading resources of Microfrontend "My First Microfrontend" failed!', e);
        return;
    }

    // Start Microfrontend
    const renderFunction = (window as any)['startMyFirstMicrofrontend'];
    if (!renderFunction) {
        console.error('OpenMicrofrontends: Render function of Microfrontend "My First Microfrontend" not found!');
        return;
    }

    
    console.info('OpenMicrofrontends: Using Shadow DOM for Microfrontend "My First Microfrontend"');
    hostElement = hostElement.attachShadow({ mode: "open" }).getRootNode() as HTMLElement;
    

    const lifecycleHooks = await renderFunction(hostElement, context);

    return {
        close: async () => {
            await lifecycleHooks?.onRemove();
            hostElement.innerHTML = '';
        },
        
        messages: context.messageBus as Microfrontend1ClientMessageBus,
        
    };
}

